apiVersion: batch.sdewan.akraino.org/v1alpha1
kind: Sdewan
metadata:
  name: example-sdewan
spec:
  # Add fields here
  node: "ubuntu18"
  networks:
    - name: ovn-priv-net
  mwan3Conf: example-mwan3conf
