# Secret resources
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  userPassword: "scc-user"
  rootPassword: "scc-root"

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-secret
type: Opaque
stringData:
  userPassword: "scc-user"
  rootPassword: "scc-root"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-data-secret
type: Opaque
stringData:
  key: "data-secret"