# SPDX-License-Identifier: Apache-2.0 
# Copyright (c) 2021 Intel Corporation
# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ipsechosts.batch.sdewan.akraino.org
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: Cg==
      service:
        namespace: system
        name: webhook-service
        path: /convert
