# permissions to do edit ipsecsites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipsecsite-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecsites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecsites/status
  verbs:
  - get
  - patch
  - update
