# permissions to do viewer ipsecsites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipsecsite-viewer-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecsites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecsites/status
  verbs:
  - get
