# permissions to do edit mwan3confs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mwan3conf-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - mwan3confs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - mwan3confs/status
  verbs:
  - get
  - patch
  - update
