# permissions to do edit sdewans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdewan-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - sdewans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - sdewans/status
  verbs:
  - get
  - patch
  - update
