---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sdewan-bucket-permission
  failurePolicy: Fail
  name: validate-sdewan-bucket.akraino.org
  rules:
  - apiGroups:
    - batch.sdewan.akraino.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - mwan3policies
    - mwan3rules
    - networkfirewallrules
    - firewallzones
    - firewallforwardings
    - firewallrules
    - firewallsnats
    - firewalldnats
    - cnfnats
    - cnfroutes
    - cnfrouterules
    - cnfservices
    - cnflocalservices
    - cnfhubsites
    - cnfstatuses
    - sdewanapplication
    - ipsecproposals
    - ipsechosts
    - ipsecsites
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-label
  failurePolicy: Fail
  name: validate-label.akraino.org
  rules:
  - apiGroups:
    - apps
    - batch.sdewan.akraino.org
    apiVersions:
    - v1
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - deployments
    - mwan3policies
    - mwan3rules
    - networkfirewallrules
    - firewallzones
    - firewallforwardings
    - firewallrules
    - firewallsnats
    - firewalldnats
    - cnfnats
    - cnfservices
    - cnfroutes
    - cnfrouterules
    - cnflocalservices
    - cnfhubsites
    - cnfstatuses
    - sdewanapplication
    - ipsecproposals
    - ipsechosts
    - ipsecsites
  sideEffects: None
