# permissions for end users to edit cnfroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnfroute-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - cnfroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - cnfroutes/status
  verbs:
  - get
