# SPDX-License-Identifier: Apache-2.0 
# Copyright (c) 2021 Intel Corporation
# permissions for end users to view cnfrouterules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnfrouterule-viewer-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - cnfrouterules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - cnfrouterules/status
  verbs:
  - get
