# permissions for end users to view cnfservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnfservice-viewer-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - cnfservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - cnfservices/status
  verbs:
  - get
