# permissions to do viewer ipsechosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipsechost-viewer-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsechosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsechosts/status
  verbs:
  - get
