# permissions to do viewer ipsecproposals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipsecproposal-viewer-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecproposals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecproposals/status
  verbs:
  - get
