# permissions to do edit ipsechosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipsechost-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsechosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsechosts/status
  verbs:
  - get
  - patch
  - update
