# permissions to do edit ipsecproposals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipsecproposal-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecproposals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecproposals/status
  verbs:
  - get
  - patch
  - update
