# permissions for end users to edit mwan3rules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mwan3rule-editor-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - mwan3rules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - mwan3rules/status
  verbs:
  - get
