
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewalldnats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewalldnats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallforwardings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallforwardings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallsnats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallsnats/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - firewallzones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecproposals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsecproposals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsechosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - ipsechosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - mwan3policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - mwan3policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - mwan3rules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - mwan3rules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
