# permissions for end users to view sdewanapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdewanapplication-viewer-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - sdewanapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - sdewanapplications/status
  verbs:
  - get
