# SPDX-License-Identifier: Apache-2.0 
# Copyright (c) 2021 Intel Corporation
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-intent
  annotations:
    sdewan-bucket-type-permission: |-
      { "mwan3rules": ["app-intent", "k8s-service"],
        "mwan3policies": ["*"],
        "firewall*": ["app-intent"]
      }
rules:
- apiGroups: ["batch.sdewan.akraino.org"]
  resources:
  - mwan3policies
  - mwan3rules
  - firewallzones
  - firewallforwardings
  - firewallsnats
  - firewalldnats
  - firewallrules
  verbs: ["create", "get", "watch", "list", "delete"]
