# SPDX-License-Identifier: Apache-2.0 
# Copyright (c) 2021 Intel Corporation
apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: ProviderNetwork
metadata:
  name: pnetwork
spec:
  cniType: ovn4nfv
  ipv4Subnets:
  - subnet: 10.10.70.0/24
    name: subnet1
    gateway: 10.10.70.1/24
    excludeIps: 10.10.70.2 10.10.70.5..10.10.70.10
  providerNetType: VLAN
  vlan:
    vlanId: "100"
    providerInterfaceName: eth1
    logicalInterfaceName: eth1.100
    vlanNodeSelector: specific
    nodeLabelList:
    - kubernetes.io/hostname=ubuntu18
