# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
apiVersion: k8s.plugin.opnfv.org/v1alpha1
kind: Network
metadata:
  name: ovn-network
spec:
  cniType : ovn4nfv
  ipv4Subnets:
  - subnet: 172.16.70.0/24
    name: subnet1
    gateway: 172.16.70.1/24
