# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sdewan-serving-cert
  namespace: {{ .Values.namespace }}
spec:
  dnsNames:
  - sdewan-webhook-service.{{ .Values.namespace }}.svc
  - sdewan-webhook-service.{{ .Values.namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: sdewan-selfsigned-issuer
  secretName: webhook-server-cert
