# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sdewan-selfsigned-issuer
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}

