# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: {{ .Values.spec.label }}
  name: sdewan-controller-manager-metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: {{ .Values.spec.label }}
---
apiVersion: v1
kind: Service
metadata:
  name: sdewan-webhook-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: {{ .Values.spec.label }}
